In [3]:
import tensorflow as tf

In [149]:
#常数
y = tf.constant(23,name='y')
#变量
y2 = tf.Variable(23,name='y2')
y3 = tf.placeholder(tf.int32) #占位符，类似形参

init = tf.global_variables_initializer() #初始化节点
sess = tf.Session()
sess.run(init)
print(sess.run(y),sess.run(y2))

z = tf.identity(y3) #占位符无法引用自身，放入计算图至少需要一个操作
value = 23
print(sess.run(z,feed_dict={y3:value}))

23 23
23


In [150]:
import tensorflow as tf
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)
add = tf.add(x, y)
mul = tf.multiply(x, y)

with tf.Session() as sess:
    print(sess.run(add, feed_dict={x: 2, y: 3}))
    print(sess.run(mul, feed_dict={x: 2, y: 3}))

5
6


In [158]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
product = tf.matmul(matrix1, matrix2)
add = tf.add(matrix1, matrix2)
with tf.Session() as sess:
    result1 = sess.run(product)
    result2 = sess.run(add)
    print(result1,result2)

[[12.]] [[5. 5.]
 [5. 5.]]


In [151]:
def linear_function():
    np.random.seed(1)
    X = tf.constant(np.random.randn(3,1),name='X')
    W = tf.constant(np.random.randn(4,3),name='W')
    b = tf.constant(np.random.randn(4,1),name='b')
    Y = tf.add(tf.matmul(W,X),b)
    a = tf.constant(2)
    sess = tf.Session()
    result = sess.run(Y)
    sess.close()
    return result
print(str(linear_function()))

[[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


In [68]:
def sigmoid(z):
    x = tf.placeholder(tf.float32,name = "x")
    sigmoid = tf.sigmoid(x)
    with tf.Session() as sess:
        result = sess.run(sigmoid,feed_dict = {x:z})
    return result
print(sigmoid(2))

0.880797


In [111]:
def sigmoid(x):
    return 1.0/(1+np.exp(-x))

y2 = np.array([[1,0,0],[0,1,0],[0,0,1],[1,1,0],[0,1,0]])
logit2 = np.array([[12,3,2],[3,10,1],[1,2,5],[4,6.5,1.2],[3,6,1]])

y2 = np.array(y2).astype(np.float64)
sess=tf.Session()
cost = tf.nn.sigmoid_cross_entropy_with_logits(labels=y2, logits=logit2)


In [152]:
def one_hot_matrix(labels,C):
    depth = tf.constant(value=C,name='C')
    one_hot_matrix = tf.one_hot(labels,depth,axis=0)
    sess = tf.Session()

    one_hot = sess.run(one_hot_matrix)
    sess.close()
    return one_hot

labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels, C = 4)
#4x6矩阵，四行分别对应0，1，2，3；元素为1表示出现的位置
print (str(one_hot)) 

[[0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [117]:
def ones(shape):
    ones = tf.ones(3)
    sess = tf.Session()
    ones = sess.run(ones)

    sess.close()
    return ones
print('ones ='+str(ones([3])))

ones =[1. 1. 1.]


In [118]:
# -*- coding: utf-8 -*-
import tensorflow as tf
import numpy as np

x_data = np.random.rand(100).astype(np.float32)
y_data = x_data*0.1+0.3
print (x_data.shape)
xs = tf.placeholder(tf.float32)
ys = tf.placeholder(tf.float32)
W = tf.Variable(1.0)
#W = tf.Variable(tf.random_uniform([1],-1.0,1))
b = tf.Variable(tf.zeros([1]))
y_pre = W*xs+b

loss = tf.reduce_mean((tf.square(ys-y_pre)))

train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
for i in range(1000):
    sess.run(train_step,feed_dict={xs:x_data,ys:y_data})
    if i%50 == 0:
        print (sess.run(W),sess.run(b))

(100,)
Instructions for updating:
Use `tf.global_variables_initializer` instead.
0.9673314 [-0.03126341]
0.48626995 [0.08869851]
0.2848784 [0.19886586]
0.18848737 [0.25159472]
0.14235221 [0.27683204]
0.1202708 [0.28891128]
0.109702095 [0.29469267]
0.10464371 [0.29745975]
0.1022226 [0.2987842]
0.10106378 [0.2994181]
0.100509144 [0.2997215]
0.10024368 [0.2998667]
0.10011664 [0.2999362]
0.10005582 [0.29996946]
0.10002676 [0.29998535]
0.10001288 [0.29999298]
0.100006215 [0.29999664]
0.100003086 [0.29999834]
0.10000146 [0.2999992]
0.1000008 [0.29999954]


In [119]:
import tensorflow as tf
import numpy as np

x_data = np.random.rand(100).astype(np.float)
y_data = x_data*0.3+0.1

W = tf.Variable(tf.zeros([1]))
b = tf.Variable(tf.zeros([1]))

y_pre = W*x_data+b
loss = tf.reduce_mean(tf.square(y_data-y_pre))
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
for i in range(1000):
    sess.run(train_step)
    print(sess.run(W),sess.run(b))

[0.15489498] [0.2511416]
[0.12930092] [0.17310469]
[0.15193878] [0.18599911]
[0.16019374] [0.17459404]
[0.17131877] [0.17043515]
[0.18066332] [0.1648303]
[0.18957615] [0.16012247]
[0.19775574] [0.15563212]
[0.20534799] [0.1515112]
[0.21237136] [0.1476862]
[0.21887499] [0.14414778]
[0.22489555] [0.14087121]
[0.2304694] [0.13783802]
[0.23562957] [0.13502988]
[0.2404068] [0.13243017]
[0.24482948] [0.13002338]
[0.24892393] [0.1277952]
[0.2527145] [0.1257324]
[0.25622377] [0.12382268]
[0.2594726] [0.1220547]
[0.26248032] [0.12041792]
[0.2652648] [0.11890262]
[0.26784265] [0.11749978]
[0.2702292] [0.11620105]
[0.27243862] [0.1149987]
[0.27448407] [0.11388557]
[0.2763777] [0.11285507]
[0.27813083] [0.11190104]
[0.27975383] [0.11101781]
[0.28125638] [0.11020013]
[0.28264743] [0.10944314]
[0.28393525] [0.10874232]
[0.2851275] [0.10809351]
[0.28623125] [0.10749286]
[0.28725308] [0.10693677]
[0.2881991] [0.10642197]
[0.2890749] [0.10594536]
[0.2898857] [0.10550413]
[0.29063633] [0.10509564]
[0.29

[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986] [0.10000007]
[0.29999986]

Fork from https://github.com/aymericdamien/TensorFlow-Examples

In [165]:
from __future__ import print_function
import tensorflow as tf
from tensorflow.contrib import rnn

# Import MNIST data
from tensorflow.examples.tutorials.mnist import input_data
# mnist = input_data.read_data_sets("/Users/shengwan/Desktop/MNIST_data", one_hot=True)
# Need to download mnist data first and import from your file
MNIST_data_folder='/Users/shengwan/Desktop/MNIST_data'  
mnist=input_data.read_data_sets(MNIST_data_folder,one_hot=True)

'''
To classify images using a recurrent neural network, we consider every image
row as a sequence of pixels. Because MNIST image shape is 28*28px, we will then
handle 28 sequences of 28 steps for every sample.
'''

# Training Parameters
learning_rate = 0.001
training_steps = 10000
batch_size = 128
display_step = 200

# Network Parameters
num_input = 28 # MNIST data input (img shape: 28*28)
timesteps = 28 # timesteps
num_hidden = 128 # hidden layer num of features
num_classes = 10 # MNIST total classes (0-9 digits)

# tf Graph input
X = tf.placeholder("float", [None, timesteps, num_input])
Y = tf.placeholder("float", [None, num_classes])

# Define weights
weights = {
    'out': tf.Variable(tf.random_normal([num_hidden, num_classes]))
}
biases = {
    'out': tf.Variable(tf.random_normal([num_classes]))
}


def RNN(x, weights, biases):

    # Prepare data shape to match `rnn` function requirements
    # Current data input shape: (batch_size, timesteps, n_input)
    # Required shape: 'timesteps' tensors list of shape (batch_size, n_input)

    # Unstack to get a list of 'timesteps' tensors of shape (batch_size, n_input)
    x = tf.unstack(x, timesteps, 1)

    # Define a lstm cell with tensorflow
    lstm_cell = rnn.BasicLSTMCell(num_hidden, forget_bias=1.0)

    # Get lstm cell output
    outputs, states = rnn.static_rnn(lstm_cell, x, dtype=tf.float32)

    # Linear activation, using rnn inner loop last output
    return tf.matmul(outputs[-1], weights['out']) + biases['out']

logits = RNN(X, weights, biases)
prediction = tf.nn.softmax(logits)

# Define loss and optimizer
loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=logits, labels=Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)

# Evaluate model (with test logits, for dropout to be disabled)
correct_pred = tf.equal(tf.argmax(prediction, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

# Start training
with tf.Session() as sess:

    # Run the initializer
    sess.run(init)

    for step in range(1, training_steps+1):
        batch_x, batch_y = mnist.train.next_batch(batch_size)
        # Reshape data to get 28 seq of 28 elements
        batch_x = batch_x.reshape((batch_size, timesteps, num_input))
        # Run optimization op (backprop)
        sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
        if step % display_step == 0 or step == 1:
            # Calculate batch loss and accuracy
            loss, acc = sess.run([loss_op, accuracy], feed_dict={X: batch_x,
                                                                 Y: batch_y})
            print("Step " + str(step) + ", Minibatch Loss= " + \
                  "{:.4f}".format(loss) + ", Training Accuracy= " + \
                  "{:.3f}".format(acc))

    print("Optimization Finished!")

    # Calculate accuracy for 128 mnist test images
    test_len = 128
    test_data = mnist.test.images[:test_len].reshape((-1, timesteps, num_input))
    test_label = mnist.test.labels[:test_len]
    print("Testing Accuracy:", \
        sess.run(accuracy, feed_dict={X: test_data, Y: test_label}))

Extracting /Users/shengwan/Desktop/MNIST_data/train-images-idx3-ubyte.gz
Extracting /Users/shengwan/Desktop/MNIST_data/train-labels-idx1-ubyte.gz
Extracting /Users/shengwan/Desktop/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting /Users/shengwan/Desktop/MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

Step 1, Minibatch Loss= 2.9953, Training Accuracy= 0.102
Step 200, Minibatch Loss= 2.1417, Training Accuracy= 0.273
Step 400, Minibatch Loss= 1.9960, Training Accuracy= 0.352
Step 600, Minibatch Loss= 1.8255, Training Accuracy= 0.383
Step 800, Minibatch Loss= 1.6349, Training Accuracy= 0.500
Step 1000, Minibatch Loss= 1.4520, Training Accuracy= 0.555
Step 1200, Minibatch Loss= 1.4540, Training Accuracy= 0.531
Step 1400, Minibatch Loss= 1.3627, Training Accuracy= 0.562
Step 1600, Minibatch Loss= 1.3778, Training Accu